using System.Text.Json.Serialization;

namespace AIFlashcardMaker;

// ===========================================================================
// Research Lab — Phase 4C (Slice 1): Computed Results persistence.
//
// Stores the OUTPUT of an already-computed categorical/rank/Spearman analysis
// as a flat, JSON-safe record, so results survive closing and reopening a
// project. This file intentionally does NOT touch inference math or
// eligibility — it only carries already-computed display strings.
//
// HARD RULES (audit-critical):
//   * Every field here is a plain string/bool/DateTime — NOT the polymorphic
//     IInferenceExportable engine result. The three engine result types
//     (CategoricalTestResult / RankTestResult / SpearmanResult) are never
//     serialized directly; only their already-rendered ToPlainText()/ToCsv()
//     output (both already aggregate-only, audited in Phase 4B QA) is stored.
//   * No raw participant rows, no AI, no HTTP, no logging, no randomness.
//   * No WPF dependency — plain data + a couple of pure conversion helpers.
// ===========================================================================

public sealed class SavedComputedResult
{
    public string Id { get; set; } = Guid.NewGuid().ToString("N");

    // Display fields — mirror the in-memory Computed Results card exactly.
    public string TestName { get; set; } = "";
    public string Variables { get; set; } = "";
    public string ValidNDisplay { get; set; } = "";
    public string PValueDisplay { get; set; } = "";
    public string EffectDisplay { get; set; } = "";
    public string SignificanceText { get; set; } = "";
    public string SignificanceKind { get; set; } = "Muted";   // "Good" | "Muted"
    public bool HasPValue { get; set; }
    public bool IsSignificant { get; set; }

    // Lookup fields — used by a later slice's Re-run to relocate the pairing.
    // Not used for display; kept here now so Slice 1's saved shape is already
    // Re-run-ready without a second migration.
    public string OutcomeName { get; set; } = "";
    public string PredictorName { get; set; } = "";

    // Full rendered output — aggregate-only (contingency/group/rank-sum tables,
    // never participant rows), produced once at compute time by the engine's
    // own ToPlainText()/ToCsv(). Stored verbatim; never regenerated by AI.
    public string FullPlainText { get; set; } = "";
    public string CsvText { get; set; } = "";

    // Fixed audit line, stored explicitly (not just implied) so exports/older
    // readers of the saved JSON can see the guarantee without re-deriving it.
    public string AuditNote { get; set; } = "Computed locally · deterministic · no AI.";

    public DateTime ComputedAt { get; set; } = DateTime.UtcNow;

    // The Statistics fingerprint (sheet meaning + dataset file hash + target
    // sample size) at the moment this was computed — reused as-is from
    // StatisticsFingerprint.Compute. Stale-comparison UI is a later slice;
    // stored now so nothing needs to be re-computed retroactively.
    public string AnalysisFingerprint { get; set; } = "";

    [JsonIgnore]
    public string ComputedTimeDisplay =>
        ComputedAt.ToLocalTime().ToString("MMM d, yyyy · h:mm tt", System.Globalization.CultureInfo.InvariantCulture);
}
